title: trying to keep it simple

description: powered by the minimal theme for GitHub Pages
google_analytics:

sass: 
  load_paths:
    - node_modules
    - ../node_modules/

include: ["node_modules/tailwindcss"]

plugins:
  - jekyll-postcss

gems:
  - jekyll-seo-tag